language: android

notifications:
  email:
    on_success: always
    on_failure: always

android:
  components:
    - tools
    - build-tools-25.0.2
    - android-25
    - extra

jdk:
  - oraclejdk8

script:
   - ./gradlew clean jacocoTestReport coveralls
