language: android

notifications:
  email:
    on_success: always
    on_failure: always

branches:
  only:
  - master
  - development

android:
  components:
    - tools
    - build-tools-27.0.3
    - android-27
    - extra

jdk:
  - oraclejdk8

script:
   - ./gradlew clean jacocoTestReport coveralls
